// Generated by Selenium IDE
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using NUnit.Framework;

[TestFixture]
public class SearchGoogleTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void Lauchdemoaspnetsite()
    {
        // Test name: SearchGoogle
        // Step # | name | target | value
        // 1 | open | / | 
        driver.Navigate().GoToUrl("https://demowf.aspnetawesome.com");
        // 2 | setWindowSize | 1200x770 | 
        driver.Manage().Window.Maximize();
        driver.FindElement(By.Id("ContentPlaceHolder1_Meal")).SendKeys("TOMATO");
        IWebElement webElement = driver.FindElement(By.XPath("ContentPlaceHolder1_AllMealsCombo - awed"));
        webElement.Clear();
        webElement.SendKeys("Almonds");

        // 3 | click | name=q | 
        //driver.FindElement(By.Name("q")).Click();
        // 4 | type | name=q | Selenium
        //driver.FindElement(By.Name("q")).SendKeys("Selenium");
        // 5 | click | css=.sbhl .sbl1 > span | 
        //driver.FindElement(By.CssSelector(".sbhl .sbl1 > span")).Click();
    }
}
